global:
  scrape_interval:     15s # default
  evaluation_interval: 15s # default

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    # scrape_interval: 5s # use this if we want to overwrite the global default
    static_config:
      - targets: ['otel-collector-gateway:8889']